"""initial schema

Revision ID: 149fc56b9af9
Revises: 
Create Date: 2026-08-09 15:18:55.632090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '149fc56b9af9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolios',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_portfolios')),
    sa.UniqueConstraint('key', name=op.f('uq_portfolios_key'))
    )
    op.create_table('agent_definitions',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'retired', name='agent_definition_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_agent_definitions_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_definitions')),
    sa.UniqueConstraint('portfolio_id', 'key', name='agent_portfolio_key')
    )
    op.create_index(op.f('ix_agent_definitions_portfolio_id'), 'agent_definitions', ['portfolio_id'], unique=False)
    op.create_table('market_actors',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('website', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_market_actors_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_market_actors')),
    sa.UniqueConstraint('portfolio_id', 'name', name='market_actor_portfolio_name')
    )
    op.create_index(op.f('ix_market_actors_portfolio_id'), 'market_actors', ['portfolio_id'], unique=False)
    op.create_table('reference_sources',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('document', 'spreadsheet', 'webpage', 'interview', 'dataset', 'observation', 'report', 'other', name='source_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('locator', sa.Text(), nullable=False),
    sa.Column('publisher', sa.String(length=240), nullable=True),
    sa.Column('published_at', sa.Date(), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_digest', sa.String(length=128), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_reference_sources_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reference_sources')),
    sa.UniqueConstraint('portfolio_id', 'locator', name='source_portfolio_locator')
    )
    op.create_index(op.f('ix_reference_sources_portfolio_id'), 'reference_sources', ['portfolio_id'], unique=False)
    op.create_table('scorecards',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'active', 'retired', name='scorecard_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('formula_description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_scorecards_scorecard_version_positive')),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_scorecards_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scorecards')),
    sa.UniqueConstraint('portfolio_id', 'name', 'version', name='scorecard_version')
    )
    op.create_index(op.f('ix_scorecards_portfolio_id'), 'scorecards', ['portfolio_id'], unique=False)
    op.create_table('workspaces',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('kind', sa.Enum('idea', 'venture', 'foundry_capability', name='workspace_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('active', 'archived', name='workspace_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_workspaces_portfolio_id_portfolios')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces')),
    sa.UniqueConstraint('portfolio_id', 'key', name='workspace_portfolio_key')
    )
    op.create_index(op.f('ix_workspaces_portfolio_id'), 'workspaces', ['portfolio_id'], unique=False)
    op.create_table('agent_versions',
    sa.Column('agent_definition_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('prompt_version', sa.String(length=160), nullable=False),
    sa.Column('toolset_version', sa.String(length=160), nullable=False),
    sa.Column('policy_version', sa.String(length=160), nullable=False),
    sa.Column('code_version', sa.String(length=160), nullable=True),
    sa.Column('provider_config', sa.JSON(), nullable=False),
    sa.Column('runtime_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_definition_id'], ['agent_definitions.id'], name=op.f('fk_agent_versions_agent_definition_id_agent_definitions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_versions')),
    sa.UniqueConstraint('agent_definition_id', 'version', name='agent_version_unique')
    )
    op.create_index(op.f('ix_agent_versions_agent_definition_id'), 'agent_versions', ['agent_definition_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('workspace_id', sa.String(length=36), nullable=True),
    sa.Column('entity_type', sa.String(length=160), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=160), nullable=False),
    sa.Column('actor', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=160), nullable=True),
    sa.Column('causation_id', sa.String(length=160), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_audit_events_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_events'))
    )
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_audit_events_correlation_id'), 'audit_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_workspace_id'), 'audit_events', ['workspace_id'], unique=False)
    op.create_index('ix_audit_workspace_time', 'audit_events', ['workspace_id', 'occurred_at'], unique=False)
    op.create_table('capability_candidates',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('problem_statement', sa.Text(), nullable=False),
    sa.Column('minimal_scope', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('observed', 'shaping', 'piloting', 'adopted', 'rejected', 'retired', name='capability_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_capability_candidates_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_candidates')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_capability_candidates_workspace_id'))
    )
    op.create_table('decisions',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('supersedes_decision_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('continue', 'pivot', 'narrow', 'stop', 'build', 'defer', 'accept_risk', 'promote', 'rollback', name='decision_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'accepted', 'superseded', 'reversed', name='decision_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['supersedes_decision_id'], ['decisions.id'], name=op.f('fk_decisions_supersedes_decision_id_decisions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_decisions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decisions'))
    )
    op.create_index(op.f('ix_decisions_supersedes_decision_id'), 'decisions', ['supersedes_decision_id'], unique=False)
    op.create_index(op.f('ix_decisions_workspace_id'), 'decisions', ['workspace_id'], unique=False)
    op.create_table('ideas',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('origin', sa.Enum('original_source', 'generated_derived', 'generated_new', 'user_added', name='idea_origin', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('external_key', sa.String(length=100), nullable=True),
    sa.Column('current_revision_id', sa.String(length=36), nullable=True),
    sa.Column('status', sa.Enum('active', 'archived', name='idea_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['current_revision_id'], ['idea_revisions.id'], name='fk_ideas_current_revision', initially='DEFERRED', deferrable=True, use_alter=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ideas_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ideas')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_ideas_workspace_id'))
    )
    op.create_index(op.f('ix_ideas_external_key'), 'ideas', ['external_key'], unique=False)
    op.create_table('ranking_snapshots',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('scorecard_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.String(length=200), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], name=op.f('fk_ranking_snapshots_portfolio_id_portfolios')),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], name=op.f('fk_ranking_snapshots_scorecard_id_scorecards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_snapshots')),
    sa.UniqueConstraint('portfolio_id', 'label', name='ranking_portfolio_label')
    )
    op.create_index(op.f('ix_ranking_snapshots_portfolio_id'), 'ranking_snapshots', ['portfolio_id'], unique=False)
    op.create_index(op.f('ix_ranking_snapshots_scorecard_id'), 'ranking_snapshots', ['scorecard_id'], unique=False)
    op.create_table('scoring_criteria',
    sa.Column('scorecard_id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=240), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('direction', sa.Enum('positive', 'penalty', name='score_direction', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('scale_min', sa.Integer(), nullable=False),
    sa.Column('scale_max', sa.Integer(), nullable=False),
    sa.Column('guidance', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('scale_min < scale_max', name=op.f('ck_scoring_criteria_criterion_scale_order')),
    sa.CheckConstraint('weight >= 0 AND weight <= 1', name=op.f('ck_scoring_criteria_criterion_weight_range')),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], name=op.f('fk_scoring_criteria_scorecard_id_scorecards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scoring_criteria')),
    sa.UniqueConstraint('scorecard_id', 'key', name='criterion_scorecard_key')
    )
    op.create_index(op.f('ix_scoring_criteria_scorecard_id'), 'scoring_criteria', ['scorecard_id'], unique=False)
    op.create_table('idea_relations',
    sa.Column('source_idea_id', sa.String(length=36), nullable=False),
    sa.Column('target_idea_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('derived_from', 'combined_with', 'duplicates', 'pivots_from', name='idea_relation_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_idea_id <> target_idea_id', name=op.f('ck_idea_relations_idea_relation_not_self')),
    sa.ForeignKeyConstraint(['source_idea_id'], ['ideas.id'], name=op.f('fk_idea_relations_source_idea_id_ideas')),
    sa.ForeignKeyConstraint(['target_idea_id'], ['ideas.id'], name=op.f('fk_idea_relations_target_idea_id_ideas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_relations')),
    sa.UniqueConstraint('source_idea_id', 'target_idea_id', 'kind', name='idea_relation_unique')
    )
    op.create_index(op.f('ix_idea_relations_source_idea_id'), 'idea_relations', ['source_idea_id'], unique=False)
    op.create_index(op.f('ix_idea_relations_target_idea_id'), 'idea_relations', ['target_idea_id'], unique=False)
    op.create_table('idea_revisions',
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=True),
    sa.Column('venture_type', sa.String(length=160), nullable=True),
    sa.Column('cluster', sa.String(length=160), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('cleaned_description', sa.Text(), nullable=False),
    sa.Column('narrowing_or_pivot', sa.Text(), nullable=True),
    sa.Column('target_customer', sa.Text(), nullable=True),
    sa.Column('business_model', sa.Text(), nullable=True),
    sa.Column('focused_mvp_scope', sa.Text(), nullable=True),
    sa.Column('estimated_mvp_weeks', sa.Float(), nullable=True),
    sa.Column('key_validation_test', sa.Text(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=True),
    sa.Column('authored_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('revision_number >= 1', name=op.f('ck_idea_revisions_revision_number_positive')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_revisions_idea_id_ideas')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_revisions')),
    sa.UniqueConstraint('idea_id', 'revision_number', name='idea_revision_number')
    )
    op.create_index(op.f('ix_idea_revisions_idea_id'), 'idea_revisions', ['idea_id'], unique=False)
    op.create_table('idea_sources',
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('inspiration', 'market_reference', 'validation', name='idea_source_role', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_idea_sources_idea_id_ideas')),
    sa.ForeignKeyConstraint(['source_id'], ['reference_sources.id'], name=op.f('fk_idea_sources_source_id_reference_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_sources')),
    sa.UniqueConstraint('idea_id', 'source_id', 'role', name='idea_source_unique')
    )
    op.create_index(op.f('ix_idea_sources_idea_id'), 'idea_sources', ['idea_id'], unique=False)
    op.create_index(op.f('ix_idea_sources_source_id'), 'idea_sources', ['source_id'], unique=False)
    op.create_table('work_items',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('decision_id', sa.String(length=36), nullable=True),
    sa.Column('parent_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('kind', sa.Enum('investigation', 'experiment', 'execution', name='work_item_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('todo', 'ready', 'in_progress', 'blocked', 'done', 'cancelled', name='work_item_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('desired_outcome', sa.Text(), nullable=True),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('owner', sa.String(length=200), nullable=True),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('budget_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('blocked_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('budget_limit IS NULL OR budget_limit >= 0', name=op.f('ck_work_items_work_item_budget_nonnegative')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_work_items_decision_id_decisions')),
    sa.ForeignKeyConstraint(['parent_id'], ['work_items.id'], name=op.f('fk_work_items_parent_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_work_items_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_work_items'))
    )
    op.create_index(op.f('ix_work_items_decision_id'), 'work_items', ['decision_id'], unique=False)
    op.create_index(op.f('ix_work_items_parent_id'), 'work_items', ['parent_id'], unique=False)
    op.create_index(op.f('ix_work_items_workspace_id'), 'work_items', ['workspace_id'], unique=False)
    op.create_table('agent_runs',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_version_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('requested', 'waiting_approval', 'running', 'succeeded', 'failed', 'cancelled', name='agent_run_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=160), nullable=True),
    sa.Column('runtime_config', sa.JSON(), nullable=False),
    sa.Column('correlation_id', sa.String(length=160), nullable=True),
    sa.Column('evalops_trace_id', sa.String(length=160), nullable=True),
    sa.Column('input_digest', sa.String(length=128), nullable=True),
    sa.Column('output_digest', sa.String(length=128), nullable=True),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], name=op.f('fk_agent_runs_agent_version_id_agent_versions')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_agent_runs_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_agent_runs_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_runs'))
    )
    op.create_index(op.f('ix_agent_runs_agent_version_id'), 'agent_runs', ['agent_version_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_correlation_id'), 'agent_runs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_evalops_trace_id'), 'agent_runs', ['evalops_trace_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_work_item_id'), 'agent_runs', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_workspace_id'), 'agent_runs', ['workspace_id'], unique=False)
    op.create_table('evidence',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('origin_work_item_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('observation', 'interview', 'experiment_result', 'analytics', 'document', 'market_research', 'external_outcome', 'artifact_review', name='evidence_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='evidence_confidence', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('captured_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['origin_work_item_id'], ['work_items.id'], name=op.f('fk_evidence_origin_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_evidence_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index(op.f('ix_evidence_origin_work_item_id'), 'evidence', ['origin_work_item_id'], unique=False)
    op.create_index(op.f('ix_evidence_workspace_id'), 'evidence', ['workspace_id'], unique=False)
    op.create_table('experiments',
    sa.Column('work_item_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('planned', 'running', 'complete', 'cancelled', name='experiment_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('method', sa.Text(), nullable=False),
    sa.Column('success_criteria', sa.Text(), nullable=False),
    sa.Column('failure_criteria', sa.Text(), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_experiments_work_item_id_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiments')),
    sa.UniqueConstraint('work_item_id', name=op.f('uq_experiments_work_item_id'))
    )
    op.create_table('idea_assessments',
    sa.Column('idea_revision_id', sa.String(length=36), nullable=False),
    sa.Column('scorecard_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_number', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='idea_assessment_confidence', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=True),
    sa.Column('grade', sa.String(length=20), nullable=True),
    sa.Column('recommendation', sa.Text(), nullable=True),
    sa.Column('pros', sa.Text(), nullable=True),
    sa.Column('cons', sa.Text(), nullable=True),
    sa.Column('revenue_year_1', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('revenue_year_3', sa.Numeric(precision=16, scale=2), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('assessed_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('assessment_number >= 1', name=op.f('ck_idea_assessments_assessment_number_positive')),
    sa.CheckConstraint('overall_score IS NULL OR (overall_score >= 0 AND overall_score <= 100)', name=op.f('ck_idea_assessments_assessment_score_range')),
    sa.ForeignKeyConstraint(['idea_revision_id'], ['idea_revisions.id'], name=op.f('fk_idea_assessments_idea_revision_id_idea_revisions')),
    sa.ForeignKeyConstraint(['scorecard_id'], ['scorecards.id'], name=op.f('fk_idea_assessments_scorecard_id_scorecards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_assessments')),
    sa.UniqueConstraint('idea_revision_id', 'scorecard_id', 'assessment_number', name='assessment_revision_scorecard_number')
    )
    op.create_index(op.f('ix_idea_assessments_idea_revision_id'), 'idea_assessments', ['idea_revision_id'], unique=False)
    op.create_index(op.f('ix_idea_assessments_scorecard_id'), 'idea_assessments', ['scorecard_id'], unique=False)
    op.create_table('idea_market_actors',
    sa.Column('idea_revision_id', sa.String(length=36), nullable=False),
    sa.Column('market_actor_id', sa.String(length=36), nullable=False),
    sa.Column('relation', sa.Enum('competitor', 'alternative', 'partner', 'benchmark', name='market_actor_relation', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['idea_revision_id'], ['idea_revisions.id'], name=op.f('fk_idea_market_actors_idea_revision_id_idea_revisions')),
    sa.ForeignKeyConstraint(['market_actor_id'], ['market_actors.id'], name=op.f('fk_idea_market_actors_market_actor_id_market_actors')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idea_market_actors')),
    sa.UniqueConstraint('idea_revision_id', 'market_actor_id', 'relation', name='idea_actor_unique')
    )
    op.create_index(op.f('ix_idea_market_actors_idea_revision_id'), 'idea_market_actors', ['idea_revision_id'], unique=False)
    op.create_index(op.f('ix_idea_market_actors_market_actor_id'), 'idea_market_actors', ['market_actor_id'], unique=False)
    op.create_table('ventures',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('source_idea_revision_id', sa.String(length=36), nullable=True),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('stage', sa.Enum('discovery', 'validation', 'build', 'pilot', 'beta', 'operating', 'paused', 'archived', name='venture_stage', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('current_focus', sa.Text(), nullable=True),
    sa.Column('budget_limit', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('budget_currency', sa.String(length=3), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['source_idea_revision_id'], ['idea_revisions.id'], name=op.f('fk_ventures_source_idea_revision_id_idea_revisions')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_ventures_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ventures')),
    sa.UniqueConstraint('workspace_id', name=op.f('uq_ventures_workspace_id'))
    )
    op.create_index(op.f('ix_ventures_source_idea_revision_id'), 'ventures', ['source_idea_revision_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('kind', sa.Enum('document', 'dataset', 'report', 'prototype', 'code', 'model', 'configuration', 'prompt', 'evaluation', 'release', 'other', name='artifact_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('name', sa.String(length=300), nullable=False),
    sa.Column('location', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(length=200), nullable=True),
    sa.Column('content_digest', sa.String(length=128), nullable=True),
    sa.Column('semantic_version', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_artifacts_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_artifacts_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_artifacts_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_agent_run_id'), 'artifacts', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_artifacts_work_item_id'), 'artifacts', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_artifacts_workspace_id'), 'artifacts', ['workspace_id'], unique=False)
    op.create_table('assumptions',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('desirability', 'viability', 'feasibility', 'usability', 'growth', 'ethics', name='assumption_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'testing', 'supported', 'refuted', 'superseded', 'accepted_risk', name='assumption_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('uncertainty', sa.Integer(), nullable=False),
    sa.Column('origin_evidence_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=200), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('importance >= 1 AND importance <= 5', name=op.f('ck_assumptions_importance_range')),
    sa.CheckConstraint('uncertainty >= 1 AND uncertainty <= 5', name=op.f('ck_assumptions_uncertainty_range')),
    sa.ForeignKeyConstraint(['origin_evidence_id'], ['evidence.id'], name=op.f('fk_assumptions_origin_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_assumptions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumptions'))
    )
    op.create_index(op.f('ix_assumptions_origin_evidence_id'), 'assumptions', ['origin_evidence_id'], unique=False)
    op.create_index(op.f('ix_assumptions_workspace_id'), 'assumptions', ['workspace_id'], unique=False)
    op.create_table('capability_uses',
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('venture_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('evidence_id', sa.String(length=36), nullable=True),
    sa.Column('outcome', sa.Enum('success', 'partial', 'failure', 'inconclusive', name='capability_use_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('time_saved_minutes', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('time_saved_minutes IS NULL OR time_saved_minutes >= 0', name=op.f('ck_capability_uses_capability_time_saved_nonnegative')),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_candidates.id'], name=op.f('fk_capability_uses_capability_id_capability_candidates')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_capability_uses_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['venture_id'], ['ventures.id'], name=op.f('fk_capability_uses_venture_id_ventures')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_capability_uses_work_item_id_work_items')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_capability_uses'))
    )
    op.create_index(op.f('ix_capability_uses_capability_id'), 'capability_uses', ['capability_id'], unique=False)
    op.create_index(op.f('ix_capability_uses_evidence_id'), 'capability_uses', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_capability_uses_venture_id'), 'capability_uses', ['venture_id'], unique=False)
    op.create_index(op.f('ix_capability_uses_work_item_id'), 'capability_uses', ['work_item_id'], unique=False)
    op.create_table('criterion_scores',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('criterion_id', sa.String(length=36), nullable=False),
    sa.Column('raw_score', sa.Float(), nullable=False),
    sa.Column('normalized_score', sa.Float(), nullable=True),
    sa.Column('weighted_contribution', sa.Float(), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['idea_assessments.id'], name=op.f('fk_criterion_scores_assessment_id_idea_assessments')),
    sa.ForeignKeyConstraint(['criterion_id'], ['scoring_criteria.id'], name=op.f('fk_criterion_scores_criterion_id_scoring_criteria')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterion_scores')),
    sa.UniqueConstraint('assessment_id', 'criterion_id', name='criterion_score_unique')
    )
    op.create_index(op.f('ix_criterion_scores_assessment_id'), 'criterion_scores', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_criterion_scores_criterion_id'), 'criterion_scores', ['criterion_id'], unique=False)
    op.create_table('decision_evidence',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_evidence_decision_id_decisions')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_decision_evidence_evidence_id_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_evidence')),
    sa.UniqueConstraint('decision_id', 'evidence_id', name='decision_evidence_unique')
    )
    op.create_index(op.f('ix_decision_evidence_decision_id'), 'decision_evidence', ['decision_id'], unique=False)
    op.create_index(op.f('ix_decision_evidence_evidence_id'), 'decision_evidence', ['evidence_id'], unique=False)
    op.create_table('evidence_sources',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('source_location', sa.String(length=500), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_sources_evidence_id_evidence')),
    sa.ForeignKeyConstraint(['source_id'], ['reference_sources.id'], name=op.f('fk_evidence_sources_source_id_reference_sources')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_sources')),
    sa.UniqueConstraint('evidence_id', 'source_id', name='evidence_source_unique')
    )
    op.create_index(op.f('ix_evidence_sources_evidence_id'), 'evidence_sources', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_evidence_sources_source_id'), 'evidence_sources', ['source_id'], unique=False)
    op.create_table('external_actions',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=160), nullable=False),
    sa.Column('adapter', sa.String(length=160), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('payload_digest', sa.String(length=128), nullable=False),
    sa.Column('idempotency_key', sa.String(length=240), nullable=False),
    sa.Column('risk', sa.Enum('internal', 'reversible_external', 'external_communication', 'financial', 'destructive', name='action_risk', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('proposed', 'awaiting_approval', 'approved', 'executing', 'succeeded', 'failed', 'rejected', 'expired', 'cancelled', name='external_action_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('estimated_cost', sa.Numeric(precision=14, scale=6), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name=op.f('ck_external_actions_action_cost_nonnegative')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_external_actions_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_external_actions_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_external_actions_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_external_actions')),
    sa.UniqueConstraint('idempotency_key', name='external_action_idempotency')
    )
    op.create_index(op.f('ix_external_actions_agent_run_id'), 'external_actions', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_external_actions_work_item_id'), 'external_actions', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_external_actions_workspace_id'), 'external_actions', ['workspace_id'], unique=False)
    op.create_table('friction_occurrences',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('work_item_id', sa.String(length=36), nullable=True),
    sa.Column('agent_run_id', sa.String(length=36), nullable=True),
    sa.Column('recurrence_key', sa.String(length=160), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('minor', 'moderate', 'major', 'blocker', name='friction_severity', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('status', sa.Enum('open', 'mitigated', 'resolved', 'accepted', name='friction_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('workaround', sa.Text(), nullable=True),
    sa.Column('time_cost_minutes', sa.Integer(), nullable=True),
    sa.Column('money_cost', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('cost_currency', sa.String(length=3), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('money_cost IS NULL OR money_cost >= 0', name=op.f('ck_friction_occurrences_friction_cost_nonnegative')),
    sa.CheckConstraint('time_cost_minutes IS NULL OR time_cost_minutes >= 0', name=op.f('ck_friction_occurrences_friction_time_nonnegative')),
    sa.ForeignKeyConstraint(['agent_run_id'], ['agent_runs.id'], name=op.f('fk_friction_occurrences_agent_run_id_agent_runs')),
    sa.ForeignKeyConstraint(['work_item_id'], ['work_items.id'], name=op.f('fk_friction_occurrences_work_item_id_work_items')),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_friction_occurrences_workspace_id_workspaces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friction_occurrences'))
    )
    op.create_index(op.f('ix_friction_occurrences_agent_run_id'), 'friction_occurrences', ['agent_run_id'], unique=False)
    op.create_index(op.f('ix_friction_occurrences_work_item_id'), 'friction_occurrences', ['work_item_id'], unique=False)
    op.create_index(op.f('ix_friction_occurrences_workspace_id'), 'friction_occurrences', ['workspace_id'], unique=False)
    op.create_index('ix_friction_recurrence_key', 'friction_occurrences', ['recurrence_key'], unique=False)
    op.create_table('ranking_entries',
    sa.Column('snapshot_id', sa.String(length=36), nullable=False),
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_ranking_entries_ranking_rank_positive')),
    sa.ForeignKeyConstraint(['assessment_id'], ['idea_assessments.id'], name=op.f('fk_ranking_entries_assessment_id_idea_assessments')),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], name=op.f('fk_ranking_entries_idea_id_ideas')),
    sa.ForeignKeyConstraint(['snapshot_id'], ['ranking_snapshots.id'], name=op.f('fk_ranking_entries_snapshot_id_ranking_snapshots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ranking_entries')),
    sa.UniqueConstraint('snapshot_id', 'idea_id', name='ranking_idea_unique'),
    sa.UniqueConstraint('snapshot_id', 'rank', name='ranking_rank_unique')
    )
    op.create_index(op.f('ix_ranking_entries_assessment_id'), 'ranking_entries', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_idea_id'), 'ranking_entries', ['idea_id'], unique=False)
    op.create_index(op.f('ix_ranking_entries_snapshot_id'), 'ranking_entries', ['snapshot_id'], unique=False)
    op.create_table('action_attempts',
    sa.Column('external_action_id', sa.String(length=36), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('started', 'succeeded', 'failed', 'unknown', name='action_attempt_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('provider_reference', sa.String(length=300), nullable=True),
    sa.Column('receipt', sa.JSON(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('attempt_number >= 1', name=op.f('ck_action_attempts_action_attempt_positive')),
    sa.ForeignKeyConstraint(['external_action_id'], ['external_actions.id'], name=op.f('fk_action_attempts_external_action_id_external_actions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_action_attempts')),
    sa.UniqueConstraint('external_action_id', 'attempt_number', name='action_attempt_number')
    )
    op.create_index(op.f('ix_action_attempts_external_action_id'), 'action_attempts', ['external_action_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('external_action_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', 'rejected', 'expired', 'revoked', name='approval_status', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('requested_by', sa.String(length=200), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=200), nullable=True),
    sa.Column('decision_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['external_action_id'], ['external_actions.id'], name=op.f('fk_approval_requests_external_action_id_external_actions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_requests')),
    sa.UniqueConstraint('external_action_id', name=op.f('uq_approval_requests_external_action_id'))
    )
    op.create_table('artifact_relations',
    sa.Column('source_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('target_artifact_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('derived_from', 'supersedes', 'input_to', 'output_of', name='artifact_relation_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_artifact_id <> target_artifact_id', name=op.f('ck_artifact_relations_artifact_relation_not_self')),
    sa.ForeignKeyConstraint(['source_artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_relations_source_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['target_artifact_id'], ['artifacts.id'], name=op.f('fk_artifact_relations_target_artifact_id_artifacts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifact_relations')),
    sa.UniqueConstraint('source_artifact_id', 'target_artifact_id', 'kind', name='artifact_relation_unique')
    )
    op.create_index(op.f('ix_artifact_relations_source_artifact_id'), 'artifact_relations', ['source_artifact_id'], unique=False)
    op.create_index(op.f('ix_artifact_relations_target_artifact_id'), 'artifact_relations', ['target_artifact_id'], unique=False)
    op.create_table('assumption_assessments',
    sa.Column('assumption_id', sa.String(length=36), nullable=False),
    sa.Column('outcome', sa.Enum('supported', 'weakened', 'refuted', 'inconclusive', name='assessment_outcome', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('confidence', sa.Enum('low', 'medium', 'high', name='assumption_assessment_confidence', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=False),
    sa.Column('assessed_by', sa.String(length=200), nullable=True),
    sa.Column('assessed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], name=op.f('fk_assumption_assessments_assumption_id_assumptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumption_assessments'))
    )
    op.create_index(op.f('ix_assumption_assessments_assumption_id'), 'assumption_assessments', ['assumption_id'], unique=False)
    op.create_table('assumption_relations',
    sa.Column('source_assumption_id', sa.String(length=36), nullable=False),
    sa.Column('target_assumption_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.Enum('derived_from', 'refines', 'contradicts', 'depends_on', name='assumption_relation_kind', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('source_assumption_id <> target_assumption_id', name=op.f('ck_assumption_relations_assumption_relation_not_self')),
    sa.ForeignKeyConstraint(['source_assumption_id'], ['assumptions.id'], name=op.f('fk_assumption_relations_source_assumption_id_assumptions')),
    sa.ForeignKeyConstraint(['target_assumption_id'], ['assumptions.id'], name=op.f('fk_assumption_relations_target_assumption_id_assumptions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assumption_relations')),
    sa.UniqueConstraint('source_assumption_id', 'target_assumption_id', 'kind', name='assumption_relation_unique')
    )
    op.create_index(op.f('ix_assumption_relations_source_assumption_id'), 'assumption_relations', ['source_assumption_id'], unique=False)
    op.create_index(op.f('ix_assumption_relations_target_assumption_id'), 'assumption_relations', ['target_assumption_id'], unique=False)
    op.create_table('criterion_score_evidence',
    sa.Column('criterion_score_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['criterion_score_id'], ['criterion_scores.id'], name=op.f('fk_criterion_score_evidence_criterion_score_id_criterion_scores')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_criterion_score_evidence_evidence_id_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_criterion_score_evidence')),
    sa.UniqueConstraint('criterion_score_id', 'evidence_id', name='criterion_evidence_unique')
    )
    op.create_index(op.f('ix_criterion_score_evidence_criterion_score_id'), 'criterion_score_evidence', ['criterion_score_id'], unique=False)
    op.create_index(op.f('ix_criterion_score_evidence_evidence_id'), 'criterion_score_evidence', ['evidence_id'], unique=False)
    op.create_table('evidence_artifacts',
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('artifact_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['artifacts.id'], name=op.f('fk_evidence_artifacts_artifact_id_artifacts')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_evidence_artifacts_evidence_id_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_artifacts')),
    sa.UniqueConstraint('evidence_id', 'artifact_id', name='evidence_artifact_unique')
    )
    op.create_index(op.f('ix_evidence_artifacts_artifact_id'), 'evidence_artifacts', ['artifact_id'], unique=False)
    op.create_index(op.f('ix_evidence_artifacts_evidence_id'), 'evidence_artifacts', ['evidence_id'], unique=False)
    op.create_table('experiment_assumptions',
    sa.Column('experiment_id', sa.String(length=36), nullable=False),
    sa.Column('assumption_id', sa.String(length=36), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assumption_id'], ['assumptions.id'], name=op.f('fk_experiment_assumptions_assumption_id_assumptions')),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], name=op.f('fk_experiment_assumptions_experiment_id_experiments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_experiment_assumptions')),
    sa.UniqueConstraint('experiment_id', 'assumption_id', name='experiment_assumption_unique')
    )
    op.create_index(op.f('ix_experiment_assumptions_assumption_id'), 'experiment_assumptions', ['assumption_id'], unique=False)
    op.create_index(op.f('ix_experiment_assumptions_experiment_id'), 'experiment_assumptions', ['experiment_id'], unique=False)
    op.create_table('friction_capabilities',
    sa.Column('friction_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('match_strength', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('match_strength >= 1 AND match_strength <= 5', name=op.f('ck_friction_capabilities_match_range')),
    sa.ForeignKeyConstraint(['capability_id'], ['capability_candidates.id'], name=op.f('fk_friction_capabilities_capability_id_capability_candidates')),
    sa.ForeignKeyConstraint(['friction_id'], ['friction_occurrences.id'], name=op.f('fk_friction_capabilities_friction_id_friction_occurrences')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friction_capabilities')),
    sa.UniqueConstraint('friction_id', 'capability_id', name='friction_capability_unique')
    )
    op.create_index(op.f('ix_friction_capabilities_capability_id'), 'friction_capabilities', ['capability_id'], unique=False)
    op.create_index(op.f('ix_friction_capabilities_friction_id'), 'friction_capabilities', ['friction_id'], unique=False)
    op.create_table('assessment_evidence',
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('evidence_id', sa.String(length=36), nullable=False),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assumption_assessments.id'], name=op.f('fk_assessment_evidence_assessment_id_assumption_assessments')),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_assessment_evidence_evidence_id_evidence')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assessment_evidence')),
    sa.UniqueConstraint('assessment_id', 'evidence_id', name='assessment_evidence_unique')
    )
    op.create_index(op.f('ix_assessment_evidence_assessment_id'), 'assessment_evidence', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_assessment_evidence_evidence_id'), 'assessment_evidence', ['evidence_id'], unique=False)
    op.create_table('decision_assessments',
    sa.Column('decision_id', sa.String(length=36), nullable=False),
    sa.Column('assessment_id', sa.String(length=36), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assessment_id'], ['assumption_assessments.id'], name=op.f('fk_decision_assessments_assessment_id_assumption_assessments')),
    sa.ForeignKeyConstraint(['decision_id'], ['decisions.id'], name=op.f('fk_decision_assessments_decision_id_decisions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_decision_assessments')),
    sa.UniqueConstraint('decision_id', 'assessment_id', name='decision_assessment_unique')
    )
    op.create_index(op.f('ix_decision_assessments_assessment_id'), 'decision_assessments', ['assessment_id'], unique=False)
    op.create_index(op.f('ix_decision_assessments_decision_id'), 'decision_assessments', ['decision_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decision_assessments_decision_id'), table_name='decision_assessments')
    op.drop_index(op.f('ix_decision_assessments_assessment_id'), table_name='decision_assessments')
    op.drop_table('decision_assessments')
    op.drop_index(op.f('ix_assessment_evidence_evidence_id'), table_name='assessment_evidence')
    op.drop_index(op.f('ix_assessment_evidence_assessment_id'), table_name='assessment_evidence')
    op.drop_table('assessment_evidence')
    op.drop_index(op.f('ix_friction_capabilities_friction_id'), table_name='friction_capabilities')
    op.drop_index(op.f('ix_friction_capabilities_capability_id'), table_name='friction_capabilities')
    op.drop_table('friction_capabilities')
    op.drop_index(op.f('ix_experiment_assumptions_experiment_id'), table_name='experiment_assumptions')
    op.drop_index(op.f('ix_experiment_assumptions_assumption_id'), table_name='experiment_assumptions')
    op.drop_table('experiment_assumptions')
    op.drop_index(op.f('ix_evidence_artifacts_evidence_id'), table_name='evidence_artifacts')
    op.drop_index(op.f('ix_evidence_artifacts_artifact_id'), table_name='evidence_artifacts')
    op.drop_table('evidence_artifacts')
    op.drop_index(op.f('ix_criterion_score_evidence_evidence_id'), table_name='criterion_score_evidence')
    op.drop_index(op.f('ix_criterion_score_evidence_criterion_score_id'), table_name='criterion_score_evidence')
    op.drop_table('criterion_score_evidence')
    op.drop_index(op.f('ix_assumption_relations_target_assumption_id'), table_name='assumption_relations')
    op.drop_index(op.f('ix_assumption_relations_source_assumption_id'), table_name='assumption_relations')
    op.drop_table('assumption_relations')
    op.drop_index(op.f('ix_assumption_assessments_assumption_id'), table_name='assumption_assessments')
    op.drop_table('assumption_assessments')
    op.drop_index(op.f('ix_artifact_relations_target_artifact_id'), table_name='artifact_relations')
    op.drop_index(op.f('ix_artifact_relations_source_artifact_id'), table_name='artifact_relations')
    op.drop_table('artifact_relations')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_action_attempts_external_action_id'), table_name='action_attempts')
    op.drop_table('action_attempts')
    op.drop_index(op.f('ix_ranking_entries_snapshot_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_idea_id'), table_name='ranking_entries')
    op.drop_index(op.f('ix_ranking_entries_assessment_id'), table_name='ranking_entries')
    op.drop_table('ranking_entries')
    op.drop_index('ix_friction_recurrence_key', table_name='friction_occurrences')
    op.drop_index(op.f('ix_friction_occurrences_workspace_id'), table_name='friction_occurrences')
    op.drop_index(op.f('ix_friction_occurrences_work_item_id'), table_name='friction_occurrences')
    op.drop_index(op.f('ix_friction_occurrences_agent_run_id'), table_name='friction_occurrences')
    op.drop_table('friction_occurrences')
    op.drop_index(op.f('ix_external_actions_workspace_id'), table_name='external_actions')
    op.drop_index(op.f('ix_external_actions_work_item_id'), table_name='external_actions')
    op.drop_index(op.f('ix_external_actions_agent_run_id'), table_name='external_actions')
    op.drop_table('external_actions')
    op.drop_index(op.f('ix_evidence_sources_source_id'), table_name='evidence_sources')
    op.drop_index(op.f('ix_evidence_sources_evidence_id'), table_name='evidence_sources')
    op.drop_table('evidence_sources')
    op.drop_index(op.f('ix_decision_evidence_evidence_id'), table_name='decision_evidence')
    op.drop_index(op.f('ix_decision_evidence_decision_id'), table_name='decision_evidence')
    op.drop_table('decision_evidence')
    op.drop_index(op.f('ix_criterion_scores_criterion_id'), table_name='criterion_scores')
    op.drop_index(op.f('ix_criterion_scores_assessment_id'), table_name='criterion_scores')
    op.drop_table('criterion_scores')
    op.drop_index(op.f('ix_capability_uses_work_item_id'), table_name='capability_uses')
    op.drop_index(op.f('ix_capability_uses_venture_id'), table_name='capability_uses')
    op.drop_index(op.f('ix_capability_uses_evidence_id'), table_name='capability_uses')
    op.drop_index(op.f('ix_capability_uses_capability_id'), table_name='capability_uses')
    op.drop_table('capability_uses')
    op.drop_index(op.f('ix_assumptions_workspace_id'), table_name='assumptions')
    op.drop_index(op.f('ix_assumptions_origin_evidence_id'), table_name='assumptions')
    op.drop_table('assumptions')
    op.drop_index(op.f('ix_artifacts_workspace_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_work_item_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_agent_run_id'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_ventures_source_idea_revision_id'), table_name='ventures')
    op.drop_table('ventures')
    op.drop_index(op.f('ix_idea_market_actors_market_actor_id'), table_name='idea_market_actors')
    op.drop_index(op.f('ix_idea_market_actors_idea_revision_id'), table_name='idea_market_actors')
    op.drop_table('idea_market_actors')
    op.drop_index(op.f('ix_idea_assessments_scorecard_id'), table_name='idea_assessments')
    op.drop_index(op.f('ix_idea_assessments_idea_revision_id'), table_name='idea_assessments')
    op.drop_table('idea_assessments')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_evidence_workspace_id'), table_name='evidence')
    op.drop_index(op.f('ix_evidence_origin_work_item_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_agent_runs_workspace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_work_item_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_evalops_trace_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_correlation_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_agent_version_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    op.drop_index(op.f('ix_work_items_workspace_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_parent_id'), table_name='work_items')
    op.drop_index(op.f('ix_work_items_decision_id'), table_name='work_items')
    op.drop_table('work_items')
    op.drop_index(op.f('ix_idea_sources_source_id'), table_name='idea_sources')
    op.drop_index(op.f('ix_idea_sources_idea_id'), table_name='idea_sources')
    op.drop_table('idea_sources')
    op.drop_index(op.f('ix_idea_revisions_idea_id'), table_name='idea_revisions')
    op.drop_table('idea_revisions')
    op.drop_index(op.f('ix_idea_relations_target_idea_id'), table_name='idea_relations')
    op.drop_index(op.f('ix_idea_relations_source_idea_id'), table_name='idea_relations')
    op.drop_table('idea_relations')
    op.drop_index(op.f('ix_scoring_criteria_scorecard_id'), table_name='scoring_criteria')
    op.drop_table('scoring_criteria')
    op.drop_index(op.f('ix_ranking_snapshots_scorecard_id'), table_name='ranking_snapshots')
    op.drop_index(op.f('ix_ranking_snapshots_portfolio_id'), table_name='ranking_snapshots')
    op.drop_table('ranking_snapshots')
    op.drop_index(op.f('ix_ideas_external_key'), table_name='ideas')
    op.drop_table('ideas')
    op.drop_index(op.f('ix_decisions_workspace_id'), table_name='decisions')
    op.drop_index(op.f('ix_decisions_supersedes_decision_id'), table_name='decisions')
    op.drop_table('decisions')
    op.drop_table('capability_candidates')
    op.drop_index('ix_audit_workspace_time', table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_workspace_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_correlation_id'), table_name='audit_events')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_agent_versions_agent_definition_id'), table_name='agent_versions')
    op.drop_table('agent_versions')
    op.drop_index(op.f('ix_workspaces_portfolio_id'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_scorecards_portfolio_id'), table_name='scorecards')
    op.drop_table('scorecards')
    op.drop_index(op.f('ix_reference_sources_portfolio_id'), table_name='reference_sources')
    op.drop_table('reference_sources')
    op.drop_index(op.f('ix_market_actors_portfolio_id'), table_name='market_actors')
    op.drop_table('market_actors')
    op.drop_index(op.f('ix_agent_definitions_portfolio_id'), table_name='agent_definitions')
    op.drop_table('agent_definitions')
    op.drop_table('portfolios')
    # ### end Alembic commands ###
