"""Explicit human input dependencies

Revision ID: b10261006001
Revises: b10261005003
Create Date: 2026-10-06 14:53:27.115953

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b10261006001"
down_revision: str | Sequence[str] | None = "b10261005003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "human_request_dependencies",
        sa.Column("target_id", sa.String(length=36), nullable=False),
        sa.Column("work_item_id", sa.String(length=36), nullable=False),
        sa.Column("satisfied_response_id", sa.String(length=36), nullable=True),
        sa.Column("other_causes", sa.JSON(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["satisfied_response_id"],
            ["artifacts.id"],
            name=op.f("fk_human_request_dependencies_satisfied_response_id_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["human_request_targets.id"],
            name=op.f("fk_human_request_dependencies_target_id_human_request_targets"),
        ),
        sa.ForeignKeyConstraint(
            ["work_item_id"],
            ["work_items.id"],
            name=op.f("fk_human_request_dependencies_work_item_id_work_items"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_human_request_dependencies")),
        sa.UniqueConstraint(
            "target_id", "work_item_id", name="request_work_dependency"
        ),
    )
    op.create_index(
        op.f("ix_human_request_dependencies_target_id"),
        "human_request_dependencies",
        ["target_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_human_request_dependencies_work_item_id"),
        "human_request_dependencies",
        ["work_item_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_human_request_dependencies_work_item_id"),
        table_name="human_request_dependencies",
    )
    op.drop_index(
        op.f("ix_human_request_dependencies_target_id"),
        table_name="human_request_dependencies",
    )
    op.drop_table("human_request_dependencies")
    # ### end Alembic commands ###
